[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = ["dotnet restore", "dotnet publish --configuration Release --output ./publish"]

[phases.start]
cmd = "dotnet ./publish/GoodVibesBackend.dll --urls http://0.0.0.0:$PORT"