name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name
  workflow_dispatch:  # Allows manual triggering

env:
  DOTNET_VERSION: '9.0.x'  # Your .NET version
  AZURE_WEBAPP_NAME: 'goodvibes-backend'  # Change this to your Azure App Service name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
